spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/island-java?useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: password
server:
  port: 8080
#logging:
#  level:
#    root: warn
#    com.example.demo.Dao: trace
#  pattern:
#    console: '%p%m%n'
